########################
# HOMEPAGE CONTROL
########################

## HOW TO
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename in your `content/home/` folder.

## CONTENT
## Navigation panel
[[main]]
  name = ""
  url = "#hero"
  weight = 1

[[main]]
  name = "ABOUT"
  url = "#about"
  weight = 2

[[main]]
  name = "BLOG"
  url = "#posts"
  weight = 3
  
[[main]]
  name = "PODCAST"
  url = "#podcasts"
  weight = 4

[[main]]
  name = "PROJECTS"
  url = "#projects"
  weight = 5

[[main]]
  name = "EXPERIENCE"
  url = "#experience"
  weight = 6

[[main]]
  name = "CONTACT"
  url = "#contact"
  weight = 7

## Excess
# #[[main]]
#  name = "PUBLICATIONS"
#  url = "#publications"
# weight = X

# #[[main]]
#  name = "COURSES"
#  url = "courses/"
#  weight = X

# #[[main]]
#  name = "ACCOMPLISHMENTS"
#  url = "#accomplishments"
#  weight = X

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 80