###########################
## SETUP OF ABGROEN.COM (documentation: https://sourcethemes.com/academic/)
############################

# HOW TO
  # Alter theme, night-mode, font, etc.

## CONTENT
## Theme
theme                 = "forest"        # Choose a theme (browse user themes in `data/themes/`)
day_night             = true            # Enable users to switch between day and night mode?
font                  = "rose"          # Override the theme's font set (browse built-in font sets in `themes/academic/data/fonts/`).
font_size             = "S"             # Choose a font size (XS, S, M, L, XL)

## Basic Info
site_type             = "Person"        # Website type (SEO, see https://schema.org/Organization#subtypes)
local_business_type   = ""              # Local business type (choose from https://schema.org/LocalBusiness#subtypes)
org_name              = ""              # Organization name (defaults to the site title from `config.toml`)
description           = ""              # Description for social sharing and search engines. If undefined, superuser role is used in place.

## Site Features
highlight = true
highlight_languages   = ["r"]            # Add support for highlighting additional languages
highlight_style       = "github"         # For supported styles, see https://cdnjs.com/libraries/highlight.js/
math                  = true             # Enable LaTeX math rendering? true/false
diagram               = true             # Enable diagram rendering? true/false
privacy_pack          = false            # Privacy pack (show a cookie consent message to visitors)
# edit_page = {repo_url = "https://github.com/abgroen/blog-site", content_dir = "", repo_branch = "master", editable = {docs = false, page = false, post = false}} # Enable visitors to edit pages? `repo` defines the repository URL. `editable` defines which page types can be edited.

## Contact details (to hide a field, clear it to "")
email                 = "anders.barslund.green@gmail.com"
phone                 = "+45 61 28 32 10"
address               = {street = "Bartholins Allé 7", city = "Aarhus C", region = "", postcode = "8000", country = "Denmark", country_code = "DK"}    # ISO-codes
coordinates           = {latitude = "56.170014", longitude = "10.203253"}                 # right-click on Google Maps and choose "What's here?"
directions            = "Enter Building 13XX - we'll see!"                                # Directions for visitors to locate you
office_hours          = ["Monday 10:00 to 13:00", "Wednesday 09:00 to 10:00"]             # To remove, set to an empty list `[]`
appointment_url       = ""                                                                # Enter an optional link for booking appointments (e.g. calendly.com).
contact_links = [
  # {icon = "twitter", icon_pack = "fab", name = "DM Me", link = "https://twitter.com/Twitter"},
  {icon = "skype", icon_pack = "fab", name = "Skype", link = "skype:anders.barslund.green"},
  # {icon = "keybase", icon_pack = "fab", name = "Chat on Keybase", link = "https://keybase.io/"},
  # {icon = "comments", icon_pack = "fas", name = "Discuss on Forum", link = "https://discourse.gohugo.io"},
  # {icon = "telegram", icon_pack = "fab", name = "Telegram Me", link = "https://telegram.me/@Telegram"},
  ]

## Social
sharing_image       = ""                # Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
twitter             = ""                # Twitter username (without @). Used when a visitor shares your site on Twitter.

## Regional Settings (date and time refer to https://sourcethemes.com/academic/docs/customization/#date-format)
date_format         = "Jan 2, 2006"     #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
time_format         = "15:04"           #   Examples: "3:04 pm" or "15:04"
address_format      = "de"              #   choose from the [address_formats] list 

## Advanced
main_menu           = {align = "c", show_logo = false}    # l = left, c = center, r = right and logo options.
reading_time        = true                                # Show estimated reading time for posts? (true/false)
section_pager       = false                               # Display next/previous section pager? (true/false)
docs_section_pager  = true                                # Display pager in Docs layout (e.g. tutorials)?
sharing             = true                                # Enable in-built social sharing buttons? (true/false)
link_authors        = true                                # Link authors to their profile page? (true/false)
abstract_length     = 135                                 # Abstract length (characters) in the Compact and Portfolio Card list views. Also, see `summaryLength` in `config.toml`.
plugins_js          = []                                  # Load JS plugins. E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
# Avatars: an image that appears next to a user's name.An avatar can be uploaded as an image named `avatar` to each user's profile or fetched from Gravatar.com.
[avatar]
  gravatar          = false            # Get user avatars from Gravatar.com? (true/false)
  shape             = "circle"         # Choose a shape for avatar images. Options: circle, square.
# Available address formats.
[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}
  en-gb = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ', ', '']}
  de    = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  fr-fr = {order = ['street', 'postcode', 'city'], delimiters = ['<br>', ' ', '']}
  zh    = {order = ['postcode', 'region', 'city', 'street'], delimiters = [' ', ' ', ' ', '']}
# Configuration of publication pages.
[publications]
  date_format       = "January 2006"          # refer to https://sourcethemes.com/academic/docs/customization/#date-format, examples: "Mon, Jan 2, 2006" or "2006-01-02"
  citation_style    = "apa"                   # Citation style ("apa" or "mla")
# Configuration of project pages.
[projects]
  post_view         = 2         #   1: List, 2: Compact, 3: Card, 4: Citation (publications only)
  publication_view  = 2
  talk_view         = 2

## Comments 
[comments]
  engine            = 0         # 0: Disabled, 1: Disqus (https://disqus.com), 2: Commento (https://commento.io)
  commentable       = {page = true, post = true, docs = true, project = true, publication = true, talk = true}        # Which page types are commentable?
  [comments.disqus]
    shortname       = ""        # Paste the shortname from your Disqus dashboard.
    show_count      = true      # Show comment count in page header? (true/false)
  [comments.commento]
    url = ""                    # If self-hosting Commento, enter its URL here (e.g. "https://commento.?.com"), otherwise leave empty.

## Search
[search]
  engine = 1                    # Search provider: 0: No search engine, 1: Academic (built-in), 2: Algolia (https://www.algolia.com)
  [search.algolia]
    app_id = ""                 # Paste the values from your Algolia dashboard.
    api_key = ""
    index_name = ""
    show_logo = false

## Maps
[map]
  # Map provider:
  #   0: No map
  #   1: Google Maps: engine = 1, API: https://developers.google.com/maps/documentation/javascript/get-api-key
  #   2: OpenStreetMap (Mapnik)
  #   3: OpenStreetMap (Mapbox): engine = 3, API: https://www.mapbox.com/studio/account/tokens
  engine = 2
  api_key = ""
  zoom = 15

## Marketing
[marketing]
  google_analytics = ""
  google_tag_manager = ""