###########################
# CONFIGURATION OF ABGROEN.COM (documentation: https://sourcethemes.com/academic/)
###########################

# HOW TO
  # Alter title, url, theme, etc.

## CONTENT
title                           = "Grøn's"                                      # Title of site: top left and tab
baseurl                         = "https://www.abgroen.com/"                    # The URL of your site. End your URL with a `/` trailing slash, e.g. `https://example.com/`.
copyright                       = "Copyright `{year}`. All rights reserved."    # Enter a copyright notice to display in the site footer. To display a copyright symbol, type `&copy;`. For current year, type `{year}`.

## ADVANCED
theme                           = "hugo-academic"                               # Name of Academic theme folder in `themes/`.
enableGitInfo                   = false                                         # Get last modified date for content from Git?
defaultContentLanguage          = "en"                                          # Default language to use (if you setup multilingual support)
hasCJKLanguage                  = false                                         # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir  = false
removePathAccents               = true                                          # Workaround for https://github.com/gohugoio/hugo/issues/5687

summaryLength                   = 30                                            # Listing summary length in words. Also, see `abstract_length` in `params.toml`.
paginate                        = 10                                            # Number of items per page in paginated lists.
enableEmoji                     = true
footnotereturnlinkcontents      = "<sup>^</sup>"
ignoreFiles                     = ["\\.ipynb$", ".ipynb_checkpoints$", "\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    posts                       = "/:slug/"
    podcast                     = "/:slug/"

[outputs]
  home                          = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section                       = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes                      = ["webmanifest"]

[outputFormats.WebAppManifest]
  mediaType                     = "application/manifest+json"
  rel                           = "manifest"

[markup]
  defaultMarkdownHandler        = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe                    = true                                            # Enable user to embed HTML snippets in Markdown content.
  [markup.highlight]
    codeFences                  = false                                           # Disable Hugo's code highlighter as it conflicts with Academic's highligher.
  [markup.tableOfContents]
    startLevel                  = 2
    endLevel                    = 3

[imaging]
  resampleFilter                = "lanczos"
  quality                       = 90
  anchor                        = "smart"                                         # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag                           = "tags"
  category                      = "categories"
  publication_type              = "publication_types"
  author                        = "authors"
